# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VMPS-Server
version:      0.03
version_from: lib/VMPS/Server.pm
installdirs:  site
requires:
    Cwd:                           0
    File::Basename:                0
    File::Slurp:                   0
    Net::MAC:                      0
    Net::Server::PreFork:          0
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
